openapi: 3.0.3
info:
  title: Products Service API
  description: API AWS shop
  version: 1.0.0
servers:
  - url: https://1r4bcu3kqf.execute-api.eu-west-1.amazonaws.com/prod
paths:
  /products:
    get:
      summary: Get list of products
      description: ProductsList Endpoint
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: integer
                    count:
                      type: integer
        '400':
          description: Invalid request
        '404':
          description: Product not found
        '500':
          description: Internal server error
    post:
      summary: Create a new product
      description: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: The provided body does not match the expected schema
        '500':
          description: A database operation failed while processing the request

  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product info Endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: integer
                  count:
                    type: integer
        '400':
          description: Product id is not provided
        '404':
          description: Product with requested id doesn't exist
        '500':
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: integer
        count:
          type: integer
      required:
        - id
        - title
        - price
        - description
        - count
