openapi: 3.0.3
info:
  title: Products Service API
  description: API AWS shop
  version: 1.0.0
servers:
  - url: https://1r4bcu3kqf.execute-api.eu-west-1.amazonaws.com/prod
paths:
  /products:
    get:
      summary: Get list of products
      description: ProductsList Endpoint
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
        '400':
          description: Invalid request
        '404':
          description: Product not found
        '500':
          description: Internal server error
  
  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product info Endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
        '404':
          description: Product with requested id doesn't exist
        '500':
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number